### PR TITLE
Implimented 3 tier User System

### PR DESCRIPTION
**Pull request by thetronjohnson**
- Farmer User
- Shop User
- Customer User

Only staff user has admin panel access
Super User has access to different Models in the admin panel

Farmer/Shop/Customer cannot access Django Admin ennu parayan paranju

@ann-philip Product Model Chytekkamo

### CODE REVIEW

**Comment by athul** [comment]
Eda give me an hour, Njan test cheyth nokkam

**Comment by thetronjohnson** [comment]
Alt Text

**Comment by athul** [comment]
This closes #3  right?

**Comment by thetronjohnson** [comment]
Product Model koodi venam @ann-philip

**Comment by athul** [comment]
@thetronjohnson okay now?

**Comment by thetronjohnson** [comment]
@athul Product ilek foreign key ittitind

**Comment by thetronjohnson** [comment]
@athul merge chytekamo

**Comment by athul** [comment]
@dependabot squash and merge

**Pull request merged**
