### PR TITLE
monuse Api ita atti🤘

### PR DESCRIPTION
**Pull request by abhinavprasad47**
## Disclaimer
following code is shit and may break anytime😝❗️❗️

### CODE REVIEW

**Comment by abhinavprasad47** [comment]
monuse baki CRUD features add chaiyanam views.py il kure paniyan ind
itoke apo tirkuvo avo 😵

**Comment by athul** [comment]
@thetronjohnson can you check if these endpoints are relevant. We'll merge this after everything is set for the API.


@abhinavprasad47 oru week undallo... ath mathi

**Comment by abhinavprasad47** [comment]
Monuse itu just barenones API
Anu Vere onnum chaitatilla

**Comment by thetronjohnson** [comment]
@athul @abhinavprasad47 Oru Seminar report onnu ezhuti submit chyatte...ennit mathiyo?

**Comment by abhinavprasad47** [comment]
Set monuse

**Comment by thetronjohnson** [comment]
@athul Ella usersinum productinum endpoint ind ithil..... ini CRUD koodi pore?
LGTM  @abhinavprasad47

**Comment by abhinavprasad47** [comment]
Ada mone 🥺

**Comment by athul** [comment]
Yep...Ath mathiyaakum

:lgtm:

**Comment by thetronjohnson** [comment]
May the force be with you

**Pull request merged**
